version: "3.8"

services:
  db:
    image: postgres:15
    container_name: carrito-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apirest
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carrito-net  

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: go-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: apirest
    depends_on:
      - db
    networks:
      - carrito-net    


volumes:
  postgres_data:

networks:
  carrito-net:
    driver: bridge
